# Generated by Django 3.2.5 on 2022-02-03 21:43

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20211230_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
