# Generated by Django 5.2.7 on 2026-05-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_secret', models.CharField(help_text='Plaintext — see module docstring for rationale.', max_length=128)),
                ('name', models.CharField(help_text='Human-friendly client name shown in logs.', max_length=120)),
                ('redirect_uris', models.JSONField(default=list, help_text='Allowed redirect URIs (exact match enforced on /authorize).')),
                ('scopes', models.JSONField(default=list, help_text='Scopes this client is allowed to request. Empty means no scope restrictions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OAuth client',
                'verbose_name_plural': 'OAuth clients',
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthCode',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('redirect_uri', models.CharField(max_length=512)),
                ('code_challenge', models.CharField(help_text='PKCE code_challenge (S256).', max_length=128)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='mcp_oauth.oauthclient')),
            ],
            options={
                'verbose_name': 'OAuth authorization code',
                'verbose_name_plural': 'OAuth authorization codes',
                'indexes': [models.Index(fields=['expires_at'], name='mcp_oauth_o_expires_c294cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('token', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='mcp_oauth.oauthclient')),
            ],
            options={
                'verbose_name': 'OAuth access token',
                'verbose_name_plural': 'OAuth access tokens',
                'indexes': [models.Index(fields=['expires_at'], name='mcp_oauth_o_expires_9a2b2c_idx')],
            },
        ),
    ]
