# Generated by Django 5.2.14 on 2026-06-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='grant_types',
            field=models.JSONField(default=list, help_text="OAuth grant types the client may use. Empty falls back to ['authorization_code']."),
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='response_types',
            field=models.JSONField(default=list, help_text="OAuth response types the client may use. Empty falls back to ['code']."),
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='token_endpoint_auth_method',
            field=models.CharField(default='client_secret_post', help_text='How the client authenticates at /token: client_secret_post, client_secret_basic, or none.', max_length=32),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='client_secret',
            field=models.CharField(blank=True, default='', help_text='Plaintext — see module docstring for rationale. Empty for public (PKCE-only) clients.', max_length=128),
        ),
    ]
