# Generated by Django 5.2.7 on 2026-02-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('content_markdown', models.TextField(help_text='Privacy policy content in Markdown.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='privacy_policies', to='homepage.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
