# Generated by Django 5.2.7 on 2026-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='SEO meta description used in <meta name="description"> and og:description. Aim for 120-160 chars. Falls back to subtitle, then to a truncated description.', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Short one-liner describing what this project is. Shown on the list page card.', max_length=200),
        ),
    ]
