# Generated by Django 5.2.7 on 2026-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_project_meta_description_project_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title on first save if left blank.', max_length=160, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Short one-liner shown on the list-page card.', max_length=200)),
                ('content_markdown', models.TextField(blank=True, default='', help_text='The post body, written in Markdown.')),
                ('meta_description', models.CharField(blank=True, default='', help_text='SEO meta description used in <meta name="description"> and og:description. Aim for 120-160 chars. Falls back to subtitle, then to a truncated body.', max_length=160)),
                ('published', models.BooleanField(default=True, help_text='If False, the post is a draft — hidden from the public list and 404s on the detail page.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Defaults to first publication time. Hand-edit to reorder.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
