# Generated by Django 5.2.7 on 2026-05-30 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jesse Chen', max_length=120)),
                ('headline', models.CharField(blank=True, default='', help_text="Short tagline shown under the name, e.g. 'Software engineer building in public'.", max_length=200)),
                ('intro_markdown', models.TextField(blank=True, default='', help_text='A short bio / introduction, written in Markdown.')),
                ('photo', models.ImageField(blank=True, help_text='A photo of you. Upload here; shown in the landing hero.', null=True, upload_to='media/landing/')),
                ('project_section_title', models.CharField(default='Currently building', help_text='Heading above the featured project.', max_length=80)),
                ('featured_project_note', models.CharField(blank=True, default='', help_text="Optional override blurb for the featured project. Falls back to the project's subtitle.", max_length=200)),
                ('post_section_title', models.CharField(default='Latest writing', help_text='Heading above the featured blog post.', max_length=80)),
                ('featured_post_note', models.CharField(blank=True, default='', help_text="Optional override blurb for the featured post. Falls back to the post's subtitle/summary.", max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_post', models.ForeignKey(blank=True, help_text='The blog post / article to spotlight on the landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homepage.blogpost')),
                ('featured_project', models.ForeignKey(blank=True, help_text='The project to spotlight on the landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homepage.project')),
            ],
            options={
                'verbose_name': 'Landing page',
                'verbose_name_plural': 'Landing page',
            },
        ),
    ]
