# Generated by Django 4.1.2 on 2023-01-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_project_github_link_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
