# Generated by Django 5.2.14 on 2026-06-01 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_landingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='featured_post',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='featured_post_note',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='featured_project',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='featured_project_note',
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='post_section_title',
            field=models.CharField(default='Latest writing', help_text='Heading above the featured writing.', max_length=80),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='project_section_title',
            field=models.CharField(default='Currently building', help_text='Heading above the featured projects.', max_length=80),
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', help_text="Optional blurb shown instead of the item's own subtitle/summary.", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this row without deleting it.')),
                ('post', models.ForeignKey(blank=True, help_text='Feature a blog post. Leave blank if this row features a project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='homepage.blogpost')),
                ('project', models.ForeignKey(blank=True, help_text='Feature a project. Leave blank if this row features a post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='homepage.project')),
            ],
            options={
                'verbose_name': 'Featured item',
                'verbose_name_plural': 'Featured items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
