# Generated by Django 5.2.14 on 2026-07-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_remove_landingpage_featured_post_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="What the charge is, e.g. 'Heroku Eco dynos' or 'Postgres Essential-0'.",
                        max_length=120,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who bills you, e.g. 'Heroku', 'Neon', 'AWS'. Used for per-provider totals.",
                        max_length=60,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The charge per billing period (see cadence). Use the currency you think in.",
                        max_digits=10,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        help_text="How often you're billed. Yearly charges are divided by 12 for the monthly rollup.",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck when you cancel a charge. Inactive costs drop out of the totals but stay for history.",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional reminder, e.g. 'move to Neon free tier' or 'renews in March'.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The project this cost belongs to. Leave blank for a shared cost (e.g. a database used across several projects, or an account-level subscription).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="homepage.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project cost",
                "verbose_name_plural": "Project costs",
                "ordering": ["project__title", "-amount"],
            },
        ),
    ]
